# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Nicolas Saleille
tagline:          'Nicolas Saleille webpage'
description:      'I am an economist and a fullstack data scientist. Fond of rock climbing and technologies.'
url:              http://nsaleille.github.io/
baseurl:          /
logo : 			  /public/img/profile8.png
author:
  name:           'Nicolas Saleille'
  url:            http://nsaleille.github.io

paginate:         5
version:          2.1.0
github: https://github.com/nsaleille/
repo:   https://github.com/nsaleille/nsaleille.github.io
gems:		[jekyll-paginate, jekyll-gist]
