# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Nicolas Saleille
tagline:          'Nicolas Saleille webpage'
# description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
description:      'I am an economist and a fullstack data scientist. Fond of rock climbing and technologies. Active contributor @ayni.in'
url:              http://nsaleille.github.io/

baseurl:          /
logo : 			  /public/img/profile_pic_6.png

author:
  name:           'Nicolas Saleille'
  url:            http://nsaleille.github.io

paginate:         5
# Custom vars
version:          2.1.0

github:
repo:           https://github.com/nsaleille
gems:			[jekyll-paginate, jekyll-gist]